name: hw-hspec-hedgehog
version: '0.1.0.2'
synopsis: Interoperability between hspec and hedgehog
description: Some functions to use hedgehog from hspec
category: Web
author: John Ky
maintainer: newhoggy@gmail.com
copyright: 2017 John Ky
license: BSD3
github: githubuser/hw-hspec-hedgehog
extra-source-files:
- README.md
dependencies:
- hedgehog
- hspec
library:
  source-dirs: src
  exposed-modules:
  - HaskellWorks.Hspec.Hedgehog
  dependencies:
  - base >=4.7 && <5
  - call-stack
  - HUnit
tests:
  hw-hspec-hedgehog-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - hw-hspec-hedgehog
