name: hw-hspec-hedgehog
version: '0.1.0.6'
synopsis: Interoperability between hspec and hedgehog
description: Interoperability between hspec and hedgehog.
category: Web
author: John Ky
maintainer: newhoggy@gmail.com
copyright: 2017 John Ky
license: BSD3
github: haskell-works/hw-hspec-hedgehog
tested-with: GHC == 8.4.2, GHC == 8.2.2, GHC == 8.0.2, GHC == 7.10.3
extra-source-files:
- README.md
dependencies:
- hedgehog >= 0.5 && <0.7
- hspec >= 2.4 && < 2.6

library:
  source-dirs: src
  exposed-modules:
  - HaskellWorks.Hspec.Hedgehog
  dependencies:
  - base >=4.7 && <5
  - call-stack >= 0.1 && < 0.2
  - HUnit >= 1.5 && < 1.7
  - transformers >= 0.4 && < 0.6

tests:
  hw-hspec-hedgehog-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - hw-hspec-hedgehog
    verbatim:
      build-tool-depends: hspec-discover:hspec-discover
